espace_homepage:
    path:     /
    defaults: { _controller: EspaceBundle:Default:index }


modifier_espace_client:
    path: /client/espace/modifier{id}
    defaults: { _controller: EspaceBundle:Espace:modifierespace}

ajouter_espace_client:
    path:     /client/ajouter_espace
    defaults: { _controller: EspaceBundle:Espace:create }

ajouter_album_client:
    path:     /client/album/{id}
    defaults: { _controller: EspaceBundle:Espace:album }

espace_client:
        path:     /client/espace_client
        defaults: { _controller: EspaceBundle:Espace:afficher }

offre_espace:
       path:    /client/offre_espace
       defaults: { _controller: EspaceBundle:Espace:Liste_espace }

info_espace:
       path:    /client/info_espace/{id}
       defaults: { _controller: EspaceBundle:Espace:infoespace }

ajouter_commentaire:
       path:   /client/info_espace/commentaire/{id}
       defaults: { _controller: EspaceBundle:Espace:ajouter_commentaire }

supprimer_commentaire:
      path:  /client/info_espace/supprimer_com/{id}/{espace}
      defaults: { _controller: EspaceBundle:Espace:supprimer_commentaire}

modifier_espaceparclient:
     path:  /client/offre_espace/modifier{id_esp}
     defaults: { _controller: EspaceBundle:Espace:modifierparclient}

