<?php

namespace MainBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRecent()
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v  where 
              v.date_ajout < CURRENT_TIME () ORDER BY v.date_ajout DESC  ")->setMaxResults(3);
        return $q->getResult();

    }

    public function findparordre()
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v   ORDER BY v.date_ajout DESC  ");
        return $q->getResult();

    }

    public function findparordreASC()
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v   ORDER BY v.date_ajout ASC  ");
        return $q->getResult();

    }

    public function find_par_al()
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v   ORDER BY v.libelle ASC  ");
        return $q->getResult();

    }

    public function findthat($id)
    {
        $q=$this->getEntityManager()->createQuery("UPDATE MainBundle:Categorie e SET e.nombrePost=e.nombrePost+1 WHERE e.id=:id")
            ->setParameter('id',$id);

        return $q->getResult();
    }

    public function findthis($id)
    {
        $q=$this->getEntityManager()->createQuery("UPDATE MainBundle:Categorie e SET e.nombrePost=e.nombrePost-1 WHERE e.id=:id")
            ->setParameter('id',$id);

        return $q->getResult();
    }


    public function findplus()
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v   ORDER BY v.nombrePost DESC  ")->setMaxResults(4);
        return $q->getResult();
    }

    public function rechercheMarque($marque)
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Categorie v where 
            v.libelle like :marque")
            ->setParameter('marque', '%'.$marque.'%');
        return $q->getResult();

    }
}
