<?php

namespace MainBundle\Repository;

/**
 * Commentaire_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
