<?php

namespace MainBundle\Repository;

/**
 * Commentaire_forumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_forumRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByIdPost($id){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Commentaire_forum m WHERE m.post=:id ")
            ->setParameter(":id",$id);
        return $q->getResult();
    }



    public function calc($ids){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Commentaire_forum m WHERE m.post=:id ")
            ->setParameter(":id",$ids);
        return $q->getResult();
    }



    public function findbyidsujet($ids){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Commentaire_forum m WHERE m.post=:id ")
            ->setParameter(":id",$ids);
        return $q->getResult();
    }
}
