<?php

namespace MainBundle\Repository;

/**
 * Contenu_espaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Contenu_espaceRepository extends \Doctrine\ORM\EntityRepository
{
}
