<?php

namespace MainBundle\Repository;

/**
 * EspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findetat(){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Espace m WHERE m.etat='1' ");
        return $q->getResult();
    }
    public function findetatnon(){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Espace m WHERE m.etat='0' ");
        return $q->getResult();
    }

}
