<?php

namespace MainBundle\Repository;

/**
 * Espace_copyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Espace_copyRepository extends \Doctrine\ORM\EntityRepository
{
}
