<?php

namespace MainBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlusVu()
    {
        $query=$this->getEntityManager()
            ->createQuery(" select m from MainBundle:Evenement m ORDER BY m.vue DESC ")->setMaxResults(2);
        return $query->getResult();
    }
    public function findbydate()
    {
        $query=$this->getEntityManager()
            ->createQuery(" select d from MainBundle:Evenement d ORDER BY d.dateEvenement ");
        return $query->getResult();
    }
}
