<?php

namespace MainBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findP($evenement,$user)
    {
    $qb= $this->createQueryBuilder('l')
        ->select('l')
        ->where('l.user = :user')
        ->setParameter('user',$user)
        ->andWhere('l.evenement = :evenement')
        ->setParameter('evenement',$evenement);
    $x = $qb->getQuery()->getOneOrNullResult();
    return $x;
    }
}
