<?php

namespace MainBundle\Repository;

/**
 * Photo_espaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Photo_espaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findalbum($id){
        $q=$this->getEntityManager()
            ->createQuery("select c from MainBundle:Photo_espace c WHERE c.espace=:ide")
            ->setParameter(":ide",$id);
        return $q->getResult();
    }
}
