<?php

namespace MainBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByIdCategorie($id){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Post m WHERE m.categorie=:id ")
            ->setParameter(":id",$id);
        return $q->getResult();
    }

    public function findByIdCategorie1($id){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Post m WHERE m.categorie=:id ORDER BY m.id DESC")
            ->setParameter(":id",$id);
        return $q->getResult();
    }

    public function findPost($id){
        $q=$this->getEntityManager()
            ->createQuery("select m from MainBundle:Post m WHERE m.id=:id ")
            ->setParameter(":id",$id);
        return $q->getResult();
    }

    public function findCalcule($id)
    {
        $q = $this->getEntityManager()
            ->createQuery("select COUNT(m.id) from MainBundle:Post m WHERE m.id=:id ")->getSingleScalarResult()
            ->setParameter(":id", $id);
        return $q->getResult();
    }

    public function findRecent1($id)
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Post v  where v.categorie=:id and 
              v.datePublication < CURRENT_TIME () ORDER BY v.datePublication DESC  ")->setMaxResults(3)->setParameter(":id", $id);
        return $q->getResult();
    }


    public function rechercheMarque($marque)
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Post v where 
            v.titre=:marque")
            ->setParameter('marque',$marque);
        return $q->getResult();

    }

    public function recherchePost($marque,$id)
    {
        $q=$this->getEntityManager()->createQuery("select v from MainBundle:Post v where 
            v.titre like :marque and v.categorie=:id")
            ->setParameter('marque', '%'.$marque.'%')
        ->setParameter('id',$id);
        return $q->getResult();

    }

}
