<?php

namespace MainBundle\Repository;

use Symfony\Component\Validator\Constraints\DateTime;

/**
 * RechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("r.id"));
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countAllByYear()
    {
        $date = new \DateTime("now");
        $year = $date->format('Y');
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("r.id"));
        $qb->andWhere('YEAR(r.date) = :y')->setParameter(":y",$year);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countAllByMonth()
    {
        $date = new \DateTime("now");
        $month = $date->format('m');
        $year = $date->format('Y');
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("r.id"));
        $qb->andWhere('MONTH(r.date) = :m')->setParameter(":m",$month);
        $qb->andWhere('YEAR(r.date) = :y')->setParameter(":y",$year);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function countAllByToday()
    {
        $date = new \DateTime("now");
        $day = $date->format('d');
        $month = $date->format('m');
        $year = $date->format('Y');
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("r.id"));
        $qb->andWhere('DAY(r.date) = :d')->setParameter(":d",$day);
        $qb->andWhere('MONTH(r.date) = :m')->setParameter(":m",$month);
        $qb->andWhere('YEAR(r.date) = :y')->setParameter(":y",$year);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function statByCountry()
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("u.pays"));
        $qb->addSelect("u.pays");
        $qb->join("r.user","u","WITH");
        $qb->groupBy("u.pays");
        return $qb->getQuery()->execute();
    }
    public function statByStat($country)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select($qb->expr()->count("u.ville"));
        $qb->addSelect("u.ville");
        $qb->where("u.pays = :co")->setParameter(":co",$country);
        $qb->join("r.user","u","WITH");
        $qb->groupBy("u.ville");
        return $qb->getQuery()->execute();
    }
    public function rechercheListe()
    {
        $qb = $this->createQueryBuilder('r');
        $qb->join("r.user","u","WITH");
        return $qb->getQuery()->execute();
    }
}
